[project]
name = "3-beginer-ai-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.3",
    "opencv-python>=4.11.0.86",
    "pillow>=11.2.1",
    "streamlit>=1.45.1",
    "tensorflow>=2.19.0",
]
